### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by sjanuary** [CloudNativeJS/appmetrics-zipkin#36]
It's possible to start a zipkin server in a docker container with a 1-line command

`docker run -d -p 9411:9411 openzipkin/zipkin`

and then query it with a REST API - https://github.com/openzipkin/zipkin-api

It would be great get some simple tests running with appmetrics-zipkin.

**Comment by Eli-Goldberg** [comment]
@sjanuary 
I've opened a [PR](https://github.com/RuntimeTools/appmetrics-zipkin/pull/37).
For some reason still can't reach travis' openzipkin image

**Comment by Eli-Goldberg** [comment]
IMO this is implemented by #37

**Comment by sjanuary** [comment]
Agreed, I can open a new issue for adding more tests.
